version: "3"
services:
  koroghlu:
    container_name: koroghlu-arm
    entrypoint: "/run.sh"
    logging:
      driver: local
    build:
      context: .
      dockerfile: Dockerfile.arm
    volumes:
      - ./Volume:${VOLUME}


