version: "3"
services:
  docker-artifact:
    container_name: docker-artifact-arm
    entrypoint: "/run.sh"
    logging:
      driver: local
    build:
      context: .
      dockerfile: Dockerfile.arm
    volumes:
      - ./Volume:${VOLUME}


